//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.10 at 05:55:06 PM WEST 
//


package Crawler;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="car" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="price">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fuel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="km" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "car"
})
@XmlRootElement(name = "cars")
public class Cars {

    protected List<Cars.Car> car;

    /**
     * Gets the value of the car property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the car property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCar().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cars.Car }
     *
     *
     */
    public List<Cars.Car> getCar() {
        if (car == null) {
            car = new ArrayList<Cars.Car>();
        }
        return this.car;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="price">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fuel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="km" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "title",
            "price",
            "brand",
            "model",
            "fuel",
            "month",
            "year",
            "km"
    })
    public static class Car {

        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected Cars.Car.Price price;
        @XmlElement(required = true)
        protected String brand;
        @XmlElement(required = true)
        protected String model;
        @XmlElement(required = true)
        protected String fuel;
        @XmlElement(required = true)
        protected String month;
        protected short year;
        @XmlElement(required = true)
        protected String km;

        /**
         * Gets the value of the title property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the price property.
         *
         * @return
         *     possible object is
         *     {@link Cars.Car.Price }
         *
         */
        public Cars.Car.Price getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         *
         * @param value
         *     allowed object is
         *     {@link Cars.Car.Price }
         *
         */
        public void setPrice(Cars.Car.Price value) {
            this.price = value;
        }

        /**
         * Gets the value of the brand property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getBrand() {
            return brand;
        }

        /**
         * Sets the value of the brand property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setBrand(String value) {
            this.brand = value;
        }

        /**
         * Gets the value of the model property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getModel() {
            return model;
        }

        /**
         * Sets the value of the model property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setModel(String value) {
            this.model = value;
        }

        /**
         * Gets the value of the fuel property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getFuel() {
            return fuel;
        }

        /**
         * Sets the value of the fuel property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setFuel(String value) {
            this.fuel = value;
        }

        /**
         * Gets the value of the month property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getMonth() {
            return month;
        }

        /**
         * Sets the value of the month property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setMonth(String value) {
            this.month = value;
        }

        /**
         * Gets the value of the year property.
         *
         */
        public short getYear() {
            return year;
        }

        /**
         * Sets the value of the year property.
         *
         */
        public void setYear(short value) {
            this.year = value;
        }

        /**
         * Gets the value of the km property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getKm() {
            return km;
        }

        /**
         * Sets the value of the km property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setKm(String value) {
            this.km = value;
        }

        @Override
        public String toString() {
            return "Car{" +
                    "title='" + title + '\'' +
                    ", price=" + price +
                    ", brand='" + brand + '\'' +
                    ", model='" + model + '\'' +
                    ", fuel='" + fuel + '\'' +
                    ", month='" + month + '\'' +
                    ", year=" + year +
                    ", km='" + km + '\'' +
                    '}';
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "value"
        })
        public static class Price {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "currency")
            protected String currency;

            /**
             * Gets the value of the value property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the currency property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getCurrency() {
                return currency;
            }

            /**
             * Sets the value of the currency property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setCurrency(String value) {
                this.currency = value;
            }

            @Override
            public String toString() {
                return "Price{" +
                        "value='" + value + '\'' +
                        ", currency='" + currency + '\'' +
                        '}';
            }
        }

    }

}